export { invokeAgent } from "./model-adapter.js";
export type { InvokeOptions, AgentResult } from "./model-adapter.js";
export { AgentBase } from "./agent-base.js";
export type { AgentOptions } from "./agent-base.js";
export { loadPrompt } from "./prompts/index.js";
export { parseToolCalls, runCrossingKbSearch } from "./tool-runner.js";
export type { ToolCall, ToolResult } from "./tool-runner.js";
export { loadConfig, resolveAgent } from "./config.js";
export type { AgentConfig, CrossingConfig } from "./config.js";
export { BriefAnalyst } from "./roles/brief-analyst.js";
export type { BriefAnalyzeInput } from "./roles/brief-analyst.js";
export { TopicExpert } from "./roles/topic-expert.js";
export type { TopicExpertOpts, Round1Input, Round2Input } from "./roles/topic-expert.js";
export { Coordinator } from "./roles/coordinator.js";
export type { CoordinatorOpts, Round1SynthInput, Round2AggregateInput } from "./roles/coordinator.js";
export { ProductOverviewAgent } from "./roles/product-overview-agent.js";
export type { OverviewInput, OverviewOutput } from "./roles/product-overview-agent.js";
export { CasePlannerExpert } from "./roles/case-planner-expert.js";
export type { CaseExpertOpts, Round1Input as CaseRound1Input, Round2Input as CaseRound2Input, CaseResult } from "./roles/case-planner-expert.js";
export { CaseCoordinator } from "./roles/case-coordinator.js";
export type { SynthesizeInput } from "./roles/case-coordinator.js";
export { runCaseExpert, parseToolCalls as parseCaseToolCalls } from "./case-expert-runner.js";
export type { ToolCall as CaseToolCall, ToolExecutor, RunCaseExpertResult } from "./case-expert-runner.js";
export { WriterOpeningAgent } from "./roles/writer-opening-agent.js";
export type { WriterOpeningInput, WriterOutput, ReferenceAccountKb } from "./roles/writer-opening-agent.js";
export { WriterPracticeAgent } from "./roles/writer-practice-agent.js";
export type { WriterPracticeInput } from "./roles/writer-practice-agent.js";
export { PracticeStitcherAgent } from "./roles/practice-stitcher-agent.js";
export type { StitcherInput, StitcherOutput, StitcherCase } from "./roles/practice-stitcher-agent.js";
export { WriterClosingAgent } from "./roles/writer-closing-agent.js";
export type { WriterClosingInput } from "./roles/writer-closing-agent.js";
export { StyleCriticAgent } from "./roles/style-critic-agent.js";
export type { StyleCriticInput, StyleCriticOutput } from "./roles/style-critic-agent.js";
export { StyleDistillerStructureAgent } from "./roles/style-distiller-structure-agent.js";
export type { StructureSample, StructureDistillInput, StructureDistillOutput } from "./roles/style-distiller-structure-agent.js";
export { StyleDistillerSnippetsAgent } from "./roles/style-distiller-snippets-agent.js";
export type { SnippetBatchArticle, SnippetHarvestInput, HarvestedSnippet, SnippetHarvestOutput } from "./roles/style-distiller-snippets-agent.js";
export const VERSION = "0.2.0";
