export { invokeAgent } from "./model-adapter.js";
export type { InvokeOptions, AgentResult } from "./model-adapter.js";
export { AgentBase } from "./agent-base.js";
export type { AgentOptions } from "./agent-base.js";
export { loadPrompt } from "./prompts/index.js";
export { parseToolCalls, runCrossingKbSearch } from "./tool-runner.js";
export type { ToolCall, ToolResult } from "./tool-runner.js";
export { loadConfig, resolveAgent } from "./config.js";
export type { AgentConfig, CrossingConfig } from "./config.js";
export { BriefAnalyst } from "./roles/brief-analyst.js";
export type { BriefAnalyzeInput } from "./roles/brief-analyst.js";
export { TopicExpert } from "./roles/topic-expert.js";
export type { TopicExpertOpts, Round1Input, Round2Input } from "./roles/topic-expert.js";
export { Coordinator } from "./roles/coordinator.js";
export type { CoordinatorOpts, Round1SynthInput, Round2AggregateInput } from "./roles/coordinator.js";
export { ProductOverviewAgent } from "./roles/product-overview-agent.js";
export type { OverviewInput, OverviewOutput } from "./roles/product-overview-agent.js";
export { CasePlannerExpert } from "./roles/case-planner-expert.js";
export type { CaseExpertOpts, Round1Input as CaseRound1Input, Round2Input as CaseRound2Input, CaseResult } from "./roles/case-planner-expert.js";
export const VERSION = "0.2.0";
